# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[files]
extend-exclude = [
  "CHANGELOG.md",
]

[default]
extend-ignore-re = [
  "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
  "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]

[default.extend-words]
Flor = "Flor"
Expedito = "Expedito"
operacional = "operacional"

[default.extend-identifiers]
eDNE = "eDNE"
BA = "BA"
ba = "ba"
